export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_REQUEST_SUCCESS = "ADMIN_PRODUCT_REQUEST_SUCCESS"
export const ADMIN_PRODUCT_REQUEST_FAIL = "ADMIN_PRODUCT_REQUEST_FAIL"

