export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_REQUEST_SUCCESS = "PRODUCT_REQUEST_SUCCESS";
export const PRODUCT_REQUEST_FAIL = "PRODUCT_REQUEST_FAIL";

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_REQUEST_SUCCESS = "SINGLE_PRODUCT_REQUEST_SUCCESS";
export const SINGLE_PRODUCT_REQUEST_FAIL = "SINGLE_PRODUCT_REQUEST_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST"
export const PRODUCT_UPDATE_REQUEST_SUCCESS = "PRODUCT_UPDATE_REQUEST_SUCCESS"
export const PRODUCT_UPDATE_REQUEST_FAIL = "PRODUCT_UPDATE_REQUEST_FAIL"


export const PRODUCT_PUBLISH_UNPUBLISH_REQUEST = "PRODUCT_PUBLISH_UNPUBLISH_REQUEST"
export const PRODUCT_PUBLISH_UNPUBLISH_SUCCESS = "PRODUCT_PUBLISH_UNPUBLISH_SUCCESS"
export const PRODUCT_PUBLISH_UNPUBLISH_FAIL = "PRODUCT_PUBLISH_UNPUBLISH_FAIL"


export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_REQUEST_SUCCESS = "PRODUCT_DELETE_REQUEST_SUCCESS"
export const PRODUCT_DELETE_REQUEST_FAIL = "PRODUCT_DELETE_REQUEST_FAIL"


export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_REQUEST_SUCCESS = "ADD_PRODUCT_REQUEST_SUCCESS";
export const ADD_PRODUCT_REQUEST_FAIL = "ADD_PRODUCT_REQUEST_FAIL";