export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST"
export const FORGET_PASSWORD_REQUEST_SUCCESS = "FORGET_PASSWORD_REQUEST_SUCCESS"
export const FORGET_PASSWORD_REQUEST_FAIL = "FORGET_PASSWORD_REQUEST_FAIL"

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS"
export const SIGNUP_REQUEST_FAIL = "SIGNUP_REQUEST_FAIL"


export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST"
export const GET_ALL_USER_REQUEST_SUCCESS = "GET_ALL_USER_REQUEST_SUCCESS"
export const GET_ALL_USER_REQUEST_FAIL = "GET_ALL_USER_REQUEST_FAIL"

export const USER_ADMIN_REQUEST = "USER_ADMIN_REQUEST"
export const USER_ADMIN_REQUEST_SUCCESS = "USER_ADMIN_REQUEST_SUCCESS"
export const USER_ADMIN_REQUEST_FAIL = "USER_ADMIN_REQUEST_FAIL"

export const USER_ACTIVE_REQUEST = "USER_ACTIVE_REQUEST"
export const USER_ACTIVE_REQUEST_SUCCESS = "USER_ACTIVE_REQUEST_SUCCESS"
export const USER_ACTIVE_REQUEST_FAIL = "USER_ACTIVE_REQUEST_FAIL"

export const LOGOUT = "LOGOUT"